export default [
  { id: 1,  no: 1, policyName: 'Policy_ALSVIN_210', latestVersion: '1.2', status: 'Editing', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 2,  no: 2, policyName: 'Policy_ALSVIN_212', latestVersion: '1.0', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 3,  no: 3, policyName: 'Policy_ALSVIN_213', latestVersion: '1.0', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 4,  no: 4, policyName: 'Policy_ALSVIN_301', latestVersion: '1.1', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 5,  no: 5, policyName: 'Policy_ALSVIN_230', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 6,  no: 6, policyName: 'Policy_ALSVIN_312', latestVersion: '1.2', status: 'Editing', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 7,  no: 7, policyName: 'Policy_ALSVIN_039', latestVersion: '2.0', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 8,  no: 8, policyName: 'Policy_ALSVIN_495', latestVersion: '2.3', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 9,  no: 9, policyName: 'Policy_ALSVIN_728', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 10,  no: 10, policyName: 'Policy_ALSVIN_090', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 11,  no: 11, policyName: 'Policy_ALSVIN_320', latestVersion: '1.2', status: 'Editing', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 12,  no: 12, policyName: 'Policy_ALSVIN_574', latestVersion: '2.5', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 13,  no: 13, policyName: 'Policy_ALSVIN_923', latestVersion: '1.0', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 14,  no: 14, policyName: 'Policy_ALSVIN_609', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 15,  no: 15, policyName: 'Policy_ALSVIN_077', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 16,  no: 16, policyName: 'Policy_ALSVIN_338', latestVersion: '1.2', status: 'Editing', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 17,  no: 17, policyName: 'Policy_ALSVIN_994', latestVersion: '1.0', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 18,  no: 18, policyName: 'Policy_ALSVIN_503', latestVersion: '3.1', status: 'Pending', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 19,  no: 19, policyName: 'Policy_ALSVIN_404', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
  { id: 20,  no: 20, policyName: 'Policy_ALSVIN_107', latestVersion: '1.0', status: 'Published', updated: Date.now(), updatedBy: 'Taehyun Yoo'},
];