server:
  port: 19010

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.30.1.0:3307/autocrypt_vsoc?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: v2gadmin
    password: Autocrypt!

    hikari:
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



